version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: mongo:6.0
    container_name: db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    volumes:
      - /tmp/mongo:/data/db
