version: '3.3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - 8001:8001
    environment:
      - MONGODB_URL=mongodb://db/darqube
      - DB_NAME=darqube
    depends_on:
      - db
  db:
    image: mongo:6.0
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - /tmp/mongo:/data/db
